const protectedPostConfig = {
  title: "Posts",
  descriptionUpdate: "Update your product",
  description: "Manage your product",
  delete: "Delete",
  edit: "Edit",
  update: "Update",
  questionDelete: "Are you sure you want to delete this post?",
  warning: "This action cannot be undone.",
  cancel: "Cancel",
  confirm: "Confirm",
  tableHeader: ["Product", "Date", "Action"],
  updatePost: "Update product",
  newPost: "New One",
  successDelete: "Product deleted.",
  successCreate: "Product created.",
  successUpdate: "Product updated.",
  errorCreate: "Couldn't create product.",
  errorDelete: "Couldn't delete product.",
  errorUpdate: "Couldn't update product.",
  author: "Author",
  pleaseWait: "Please wait...",
  untitled: "Untitled",
};

export default protectedPostConfig;
